@echo off
setlocal enabledelayedexpansion

:: Settings
set "VERSION=0.0.2"
set "COLOR_COUNT=24"

:: Handle install flag
if "%~1"=="-i" goto :install
if "%~1"=="-install" goto :install
if "%~1"=="--install" goto :install

:: Parse arguments: split on -- separator, detect -d flag
set "WT_GLOBAL="
set "WT_ARGS="
set "USER_CMD="
set "HAS_DIR=0"
set "PAST_SEP=0"

:parse_args
if "%~1"=="" goto :done_parse
if "%~1"=="--" (
    set "PAST_SEP=1"
    shift
    goto :parse_args
)
if !PAST_SEP!==1 (
    if defined USER_CMD (
        set "USER_CMD=!USER_CMD! %1"
    ) else (
        set "USER_CMD=%1"
    )
    shift
    goto :parse_args
)
if /i "%~1"=="-d" (
    set "HAS_DIR=1"
    if defined WT_ARGS (
        set "WT_ARGS=!WT_ARGS! %1 %2"
    ) else (
        set "WT_ARGS=%1 %2"
    )
    shift
    shift
    goto :parse_args
)
if /i "%~1"=="-w" goto :parse_global
if /i "%~1"=="--window" goto :parse_global
goto :parse_local
:parse_global
if defined WT_GLOBAL (
    set "WT_GLOBAL=!WT_GLOBAL! %1 %2"
) else (
    set "WT_GLOBAL=%1 %2"
)
shift
shift
goto :parse_args
:parse_local
if defined WT_ARGS (
    set "WT_ARGS=!WT_ARGS! %1"
) else (
    set "WT_ARGS=%1"
)
shift
goto :parse_args
:done_parse

:: 256 embedded color pairs (generated by generate-colors.mjs)
set "TAB_0=#FF0000" & set "BG_0=#260000"
set "TAB_1=#FF0400" & set "BG_1=#260100"
set "TAB_2=#FF0D00" & set "BG_2=#260200"
set "TAB_3=#FF1100" & set "BG_3=#260300"
set "TAB_4=#FF1900" & set "BG_4=#260400"
set "TAB_5=#FF1E00" & set "BG_5=#260500"
set "TAB_6=#FF2200" & set "BG_6=#260500"
set "TAB_7=#FF2A00" & set "BG_7=#260600"
set "TAB_8=#FF2F00" & set "BG_8=#260700"
set "TAB_9=#FF3700" & set "BG_9=#260800"
set "TAB_10=#FF3C00" & set "BG_10=#260900"
set "TAB_11=#FF4000" & set "BG_11=#260A00"
set "TAB_12=#FF4800" & set "BG_12=#260B00"
set "TAB_13=#FF4D00" & set "BG_13=#260C00"
set "TAB_14=#FF5500" & set "BG_14=#260D00"
set "TAB_15=#FF5900" & set "BG_15=#260D00"
set "TAB_16=#FF6200" & set "BG_16=#260F00"
set "TAB_17=#FF6600" & set "BG_17=#260F00"
set "TAB_18=#FF6A00" & set "BG_18=#261000"
set "TAB_19=#FF7300" & set "BG_19=#261100"
set "TAB_20=#FF7700" & set "BG_20=#261200"
set "TAB_21=#FF8000" & set "BG_21=#261300"
set "TAB_22=#FF8400" & set "BG_22=#261400"
set "TAB_23=#FF8800" & set "BG_23=#261400"
set "TAB_24=#FF9100" & set "BG_24=#261600"
set "TAB_25=#FF9500" & set "BG_25=#261600"
set "TAB_26=#FF9D00" & set "BG_26=#261800"
set "TAB_27=#FFA200" & set "BG_27=#261800"
set "TAB_28=#FFA600" & set "BG_28=#261900"
set "TAB_29=#FFAE00" & set "BG_29=#261A00"
set "TAB_30=#FFB300" & set "BG_30=#261B00"
set "TAB_31=#FFBB00" & set "BG_31=#261C00"
set "TAB_32=#FFBF00" & set "BG_32=#261D00"
set "TAB_33=#FFC400" & set "BG_33=#261D00"
set "TAB_34=#FFCC00" & set "BG_34=#261F00"
set "TAB_35=#FFD000" & set "BG_35=#261F00"
set "TAB_36=#FFD900" & set "BG_36=#262100"
set "TAB_37=#FFDD00" & set "BG_37=#262100"
set "TAB_38=#FFE100" & set "BG_38=#262200"
set "TAB_39=#FFEA00" & set "BG_39=#262300"
set "TAB_40=#FFEE00" & set "BG_40=#262400"
set "TAB_41=#FFF700" & set "BG_41=#262500"
set "TAB_42=#FFFB00" & set "BG_42=#262600"
set "TAB_43=#FFFF00" & set "BG_43=#262600"
set "TAB_44=#F6FF00" & set "BG_44=#252600"
set "TAB_45=#F2FF00" & set "BG_45=#242600"
set "TAB_46=#EAFF00" & set "BG_46=#232600"
set "TAB_47=#E5FF00" & set "BG_47=#222600"
set "TAB_48=#DDFF00" & set "BG_48=#212600"
set "TAB_49=#D9FF00" & set "BG_49=#212600"
set "TAB_50=#D4FF00" & set "BG_50=#202600"
set "TAB_51=#CCFF00" & set "BG_51=#1F2600"
set "TAB_52=#C8FF00" & set "BG_52=#1E2600"
set "TAB_53=#BFFF00" & set "BG_53=#1D2600"
set "TAB_54=#BBFF00" & set "BG_54=#1C2600"
set "TAB_55=#B7FF00" & set "BG_55=#1B2600"
set "TAB_56=#AEFF00" & set "BG_56=#1A2600"
set "TAB_57=#AAFF00" & set "BG_57=#1A2600"
set "TAB_58=#A2FF00" & set "BG_58=#182600"
set "TAB_59=#9DFF00" & set "BG_59=#182600"
set "TAB_60=#99FF00" & set "BG_60=#172600"
set "TAB_61=#91FF00" & set "BG_61=#162600"
set "TAB_62=#8CFF00" & set "BG_62=#152600"
set "TAB_63=#84FF00" & set "BG_63=#142600"
set "TAB_64=#80FF00" & set "BG_64=#132600"
set "TAB_65=#7BFF00" & set "BG_65=#122600"
set "TAB_66=#73FF00" & set "BG_66=#112600"
set "TAB_67=#6FFF00" & set "BG_67=#112600"
set "TAB_68=#66FF00" & set "BG_68=#0F2600"
set "TAB_69=#62FF00" & set "BG_69=#0F2600"
set "TAB_70=#5EFF00" & set "BG_70=#0E2600"
set "TAB_71=#55FF00" & set "BG_71=#0D2600"
set "TAB_72=#51FF00" & set "BG_72=#0C2600"
set "TAB_73=#48FF00" & set "BG_73=#0B2600"
set "TAB_74=#44FF00" & set "BG_74=#0A2600"
set "TAB_75=#40FF00" & set "BG_75=#0A2600"
set "TAB_76=#37FF00" & set "BG_76=#082600"
set "TAB_77=#33FF00" & set "BG_77=#082600"
set "TAB_78=#2BFF00" & set "BG_78=#062600"
set "TAB_79=#26FF00" & set "BG_79=#062600"
set "TAB_80=#1EFF00" & set "BG_80=#052600"
set "TAB_81=#1AFF00" & set "BG_81=#042600"
set "TAB_82=#15FF00" & set "BG_82=#032600"
set "TAB_83=#0DFF00" & set "BG_83=#022600"
set "TAB_84=#09FF00" & set "BG_84=#012600"
set "TAB_85=#00FF00" & set "BG_85=#002600"
set "TAB_86=#00FF04" & set "BG_86=#002601"
set "TAB_87=#00FF08" & set "BG_87=#002601"
set "TAB_88=#00FF11" & set "BG_88=#002603"
set "TAB_89=#00FF15" & set "BG_89=#002603"
set "TAB_90=#00FF1E" & set "BG_90=#002605"
set "TAB_91=#00FF22" & set "BG_91=#002605"
set "TAB_92=#00FF26" & set "BG_92=#002606"
set "TAB_93=#00FF2F" & set "BG_93=#002607"
set "TAB_94=#00FF33" & set "BG_94=#002608"
set "TAB_95=#00FF3C" & set "BG_95=#002609"
set "TAB_96=#00FF40" & set "BG_96=#00260A"
set "TAB_97=#00FF44" & set "BG_97=#00260A"
set "TAB_98=#00FF4C" & set "BG_98=#00260B"
set "TAB_99=#00FF51" & set "BG_99=#00260C"
set "TAB_100=#00FF59" & set "BG_100=#00260D"
set "TAB_101=#00FF5E" & set "BG_101=#00260E"
set "TAB_102=#00FF62" & set "BG_102=#00260F"
set "TAB_103=#00FF6A" & set "BG_103=#002610"
set "TAB_104=#00FF6E" & set "BG_104=#002611"
set "TAB_105=#00FF77" & set "BG_105=#002612"
set "TAB_106=#00FF7B" & set "BG_106=#002612"
set "TAB_107=#00FF80" & set "BG_107=#002613"
set "TAB_108=#00FF88" & set "BG_108=#002614"
set "TAB_109=#00FF8C" & set "BG_109=#002615"
set "TAB_110=#00FF95" & set "BG_110=#002616"
set "TAB_111=#00FF99" & set "BG_111=#002617"
set "TAB_112=#00FFA2" & set "BG_112=#002618"
set "TAB_113=#00FFA6" & set "BG_113=#002619"
set "TAB_114=#00FFAA" & set "BG_114=#00261A"
set "TAB_115=#00FFB3" & set "BG_115=#00261B"
set "TAB_116=#00FFB7" & set "BG_116=#00261B"
set "TAB_117=#00FFBF" & set "BG_117=#00261D"
set "TAB_118=#00FFC3" & set "BG_118=#00261D"
set "TAB_119=#00FFC8" & set "BG_119=#00261E"
set "TAB_120=#00FFD0" & set "BG_120=#00261F"
set "TAB_121=#00FFD5" & set "BG_121=#002620"
set "TAB_122=#00FFDD" & set "BG_122=#002621"
set "TAB_123=#00FFE1" & set "BG_123=#002622"
set "TAB_124=#00FFE5" & set "BG_124=#002622"
set "TAB_125=#00FFEE" & set "BG_125=#002624"
set "TAB_126=#00FFF2" & set "BG_126=#002624"
set "TAB_127=#00FFFB" & set "BG_127=#002626"
set "TAB_128=#00FFFF" & set "BG_128=#002626"
set "TAB_129=#00FBFF" & set "BG_129=#002626"
set "TAB_130=#00F2FF" & set "BG_130=#002426"
set "TAB_131=#00EEFF" & set "BG_131=#002426"
set "TAB_132=#00E5FF" & set "BG_132=#002226"
set "TAB_133=#00E1FF" & set "BG_133=#002226"
set "TAB_134=#00DDFF" & set "BG_134=#002126"
set "TAB_135=#00D5FF" & set "BG_135=#002026"
set "TAB_136=#00D0FF" & set "BG_136=#001F26"
set "TAB_137=#00C8FF" & set "BG_137=#001E26"
set "TAB_138=#00C3FF" & set "BG_138=#001D26"
set "TAB_139=#00BFFF" & set "BG_139=#001D26"
set "TAB_140=#00B7FF" & set "BG_140=#001B26"
set "TAB_141=#00B3FF" & set "BG_141=#001B26"
set "TAB_142=#00AAFF" & set "BG_142=#001A26"
set "TAB_143=#00A6FF" & set "BG_143=#001926"
set "TAB_144=#009DFF" & set "BG_144=#001826"
set "TAB_145=#0099FF" & set "BG_145=#001726"
set "TAB_146=#0095FF" & set "BG_146=#001626"
set "TAB_147=#008CFF" & set "BG_147=#001526"
set "TAB_148=#0088FF" & set "BG_148=#001426"
set "TAB_149=#0080FF" & set "BG_149=#001326"
set "TAB_150=#007BFF" & set "BG_150=#001226"
set "TAB_151=#0077FF" & set "BG_151=#001226"
set "TAB_152=#006EFF" & set "BG_152=#001126"
set "TAB_153=#006AFF" & set "BG_153=#001026"
set "TAB_154=#0062FF" & set "BG_154=#000F26"
set "TAB_155=#005EFF" & set "BG_155=#000E26"
set "TAB_156=#0059FF" & set "BG_156=#000D26"
set "TAB_157=#0051FF" & set "BG_157=#000C26"
set "TAB_158=#004CFF" & set "BG_158=#000B26"
set "TAB_159=#0044FF" & set "BG_159=#000A26"
set "TAB_160=#0040FF" & set "BG_160=#000A26"
set "TAB_161=#003CFF" & set "BG_161=#000926"
set "TAB_162=#0033FF" & set "BG_162=#000826"
set "TAB_163=#002FFF" & set "BG_163=#000726"
set "TAB_164=#0026FF" & set "BG_164=#000626"
set "TAB_165=#0022FF" & set "BG_165=#000526"
set "TAB_166=#001EFF" & set "BG_166=#000526"
set "TAB_167=#0015FF" & set "BG_167=#000326"
set "TAB_168=#0011FF" & set "BG_168=#000326"
set "TAB_169=#0008FF" & set "BG_169=#000126"
set "TAB_170=#0004FF" & set "BG_170=#000126"
set "TAB_171=#0000FF" & set "BG_171=#000026"
set "TAB_172=#0800FF" & set "BG_172=#010026"
set "TAB_173=#0D00FF" & set "BG_173=#020026"
set "TAB_174=#1500FF" & set "BG_174=#030026"
set "TAB_175=#1900FF" & set "BG_175=#040026"
set "TAB_176=#2200FF" & set "BG_176=#050026"
set "TAB_177=#2600FF" & set "BG_177=#060026"
set "TAB_178=#2B00FF" & set "BG_178=#060026"
set "TAB_179=#3300FF" & set "BG_179=#080026"
set "TAB_180=#3700FF" & set "BG_180=#080026"
set "TAB_181=#4000FF" & set "BG_181=#0A0026"
set "TAB_182=#4400FF" & set "BG_182=#0A0026"
set "TAB_183=#4800FF" & set "BG_183=#0B0026"
set "TAB_184=#5100FF" & set "BG_184=#0C0026"
set "TAB_185=#5500FF" & set "BG_185=#0D0026"
set "TAB_186=#5D00FF" & set "BG_186=#0E0026"
set "TAB_187=#6200FF" & set "BG_187=#0F0026"
set "TAB_188=#6600FF" & set "BG_188=#0F0026"
set "TAB_189=#6F00FF" & set "BG_189=#110026"
set "TAB_190=#7300FF" & set "BG_190=#110026"
set "TAB_191=#7B00FF" & set "BG_191=#120026"
set "TAB_192=#8000FF" & set "BG_192=#130026"
set "TAB_193=#8400FF" & set "BG_193=#140026"
set "TAB_194=#8C00FF" & set "BG_194=#150026"
set "TAB_195=#9000FF" & set "BG_195=#160026"
set "TAB_196=#9900FF" & set "BG_196=#170026"
set "TAB_197=#9D00FF" & set "BG_197=#180026"
set "TAB_198=#A200FF" & set "BG_198=#180026"
set "TAB_199=#AA00FF" & set "BG_199=#1A0026"
set "TAB_200=#AE00FF" & set "BG_200=#1A0026"
set "TAB_201=#B700FF" & set "BG_201=#1B0026"
set "TAB_202=#BB00FF" & set "BG_202=#1C0026"
set "TAB_203=#BF00FF" & set "BG_203=#1D0026"
set "TAB_204=#C800FF" & set "BG_204=#1E0026"
set "TAB_205=#CC00FF" & set "BG_205=#1F0026"
set "TAB_206=#D400FF" & set "BG_206=#200026"
set "TAB_207=#D900FF" & set "BG_207=#210026"
set "TAB_208=#E100FF" & set "BG_208=#220026"
set "TAB_209=#E600FF" & set "BG_209=#230026"
set "TAB_210=#EA00FF" & set "BG_210=#230026"
set "TAB_211=#F200FF" & set "BG_211=#240026"
set "TAB_212=#F700FF" & set "BG_212=#250026"
set "TAB_213=#FF00FF" & set "BG_213=#260026"
set "TAB_214=#FF00FB" & set "BG_214=#260026"
set "TAB_215=#FF00F7" & set "BG_215=#260025"
set "TAB_216=#FF00EE" & set "BG_216=#260024"
set "TAB_217=#FF00EA" & set "BG_217=#260023"
set "TAB_218=#FF00E1" & set "BG_218=#260022"
set "TAB_219=#FF00DD" & set "BG_219=#260021"
set "TAB_220=#FF00D9" & set "BG_220=#260021"
set "TAB_221=#FF00D0" & set "BG_221=#26001F"
set "TAB_222=#FF00CC" & set "BG_222=#26001F"
set "TAB_223=#FF00C3" & set "BG_223=#26001D"
set "TAB_224=#FF00BF" & set "BG_224=#26001D"
set "TAB_225=#FF00BB" & set "BG_225=#26001C"
set "TAB_226=#FF00B3" & set "BG_226=#26001B"
set "TAB_227=#FF00AE" & set "BG_227=#26001A"
set "TAB_228=#FF00A6" & set "BG_228=#260019"
set "TAB_229=#FF00A2" & set "BG_229=#260018"
set "TAB_230=#FF009D" & set "BG_230=#260018"
set "TAB_231=#FF0095" & set "BG_231=#260016"
set "TAB_232=#FF0090" & set "BG_232=#260016"
set "TAB_233=#FF0088" & set "BG_233=#260014"
set "TAB_234=#FF0084" & set "BG_234=#260014"
set "TAB_235=#FF0080" & set "BG_235=#260013"
set "TAB_236=#FF0077" & set "BG_236=#260012"
set "TAB_237=#FF0073" & set "BG_237=#260011"
set "TAB_238=#FF006A" & set "BG_238=#260010"
set "TAB_239=#FF0066" & set "BG_239=#26000F"
set "TAB_240=#FF005D" & set "BG_240=#26000E"
set "TAB_241=#FF0059" & set "BG_241=#26000D"
set "TAB_242=#FF0055" & set "BG_242=#26000D"
set "TAB_243=#FF004C" & set "BG_243=#26000B"
set "TAB_244=#FF0048" & set "BG_244=#26000B"
set "TAB_245=#FF0040" & set "BG_245=#26000A"
set "TAB_246=#FF003C" & set "BG_246=#260009"
set "TAB_247=#FF0037" & set "BG_247=#260008"
set "TAB_248=#FF002F" & set "BG_248=#260007"
set "TAB_249=#FF002B" & set "BG_249=#260006"
set "TAB_250=#FF0022" & set "BG_250=#260005"
set "TAB_251=#FF001E" & set "BG_251=#260005"
set "TAB_252=#FF0019" & set "BG_252=#260004"
set "TAB_253=#FF0011" & set "BG_253=#260003"
set "TAB_254=#FF000D" & set "BG_254=#260002"
set "TAB_255=#FF0004" & set "BG_255=#260001"
set "TOTAL_COLORS=256"

:: Hash current directory: sum of ASCII char codes mod COLOR_COUNT, then map to evenly-spaced index
for /f %%i in ('powershell -NoProfile -Command "([int[]][char[]]'%CD%'|Measure-Object -Sum).Sum %% %COLOR_COUNT%"') do set "INDEX=%%i"
set /a "INDEX=INDEX * TOTAL_COLORS / COLOR_COUNT"

set "TAB_COLOR=!TAB_%INDEX%!"
set "BG_COLOR=!BG_%INDEX%!"

:: Write a temp script to set pane background via VT escape, then run user command
(
    echo @powershell -NoProfile -Command "Write-Host -NoNewline ([char]27+']11;%BG_COLOR%'+[char]7)"
    if defined USER_CMD echo !USER_CMD!
) > "%TEMP%\wtc_setbg.cmd"

:: Launch Windows Terminal (skip auto -d if user provided one)
:: Strip trailing backslash from %CD% to prevent \"  escaping issues in wt
set "LAUNCH_DIR=%CD%"
if "!LAUNCH_DIR:~-1!"=="\" set "LAUNCH_DIR=!LAUNCH_DIR:~0,-1!"
if !HAS_DIR!==0 (
    wt !WT_GLOBAL! -d "!LAUNCH_DIR!" --tabColor "%TAB_COLOR%" !WT_ARGS! cmd /k "call %TEMP%\wtc_setbg.cmd"
) else (
    wt !WT_GLOBAL! --tabColor "%TAB_COLOR%" !WT_ARGS! cmd /k "call %TEMP%\wtc_setbg.cmd"
)
exit /b

:install
:: call "%~dp0install.cmd"
set "SCRIPT_DIR=%~dp0"
set "SCRIPT_DIR=%SCRIPT_DIR:~0,-1%"
powershell -NoProfile -Command ^
  "$dir = '%SCRIPT_DIR%';" ^
  "$userPath = [Environment]::GetEnvironmentVariable('Path', 'User');" ^
  "if ($userPath -split ';' | Where-Object { $_ -ieq $dir }) {" ^
  "  Write-Host \"Already in PATH: $dir\"" ^
  "} else {" ^
  "  $newPath = if ($userPath) { \"$userPath;$dir\" } else { $dir };" ^
  "  [Environment]::SetEnvironmentVariable('Path', $newPath, 'User');" ^
  "  Write-Host \"Added to PATH: $dir\";" ^
  "  Write-Host 'Restart your terminal for changes to take effect.'" ^
  "}"
exit /b
